### ISSUE TITLE
Add handling of bum tar file that gets pulled down

### ISSUE THREAD

**Issue by geoderek** [SouthFACT/landsatfact-data#40]
Checking the logs this morning it seems that there is a bum tar file coming through.  This needs to be handled in the geoprocessing script as it cause it to fail.

**Comment by geoderek** [comment]
Error to investigate:

call to extractProductForCompare with: LE70310342015093EDC00
/var/vsites/landsatfact-data-dev.nemac.org/project/dataexchange
downloading...Downloading LE70310342015093EDC00 with dataset LANDSAT_ETM_SLC_OFF<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="https://earthexplorer.usgs.gov/inventory/soap" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" SOAP-ENV:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">SOAP-ENV:Bodyns1:download<datasetName xsi:type="xsd:string">LANDSAT_ETM_SLC_OFF</datasetName><apiKey xsi:type="xsd:string">5122230bb2d5456dab4d77967188805e</apiKey><node xsi:type="xsd:string">EE</node><entityIds xsi:type="ns1:ArrayOfString"><item xsi:type="xsd:string">LE70310342015093EDC00</item></entityIds><products xsi:type="ns1:ArrayOfString"><item xsi:type="xsd:string">STANDARD</item></products>/ns1:download/SOAP-ENV:Body/SOAP-ENV:Envelope
Internal Server ErrorPHP Notice:  Trying to get property of non-object in /var/v                                                                                     eneid.php on line 76
 downloadUrl->item :PHP Notice:  Trying to get property of non-object in /var/vs                                                                                     neid.php on line 77
PHP Warning:  file_get_contents(): Filename cannot be empty in /var/vsites/lands                                                                                     n line 20

Traceback (most recent call last):
  File "./landsatFACTmain.py", line 116, in <module>
    landsatFactTools_GDAL.extractProductForCompare(diff_quad[:-2],tarStorage,tif
  File "/var/vsites/landsatfact-data-dev.nemac.org/project/geoprocessing/landsat
    extractedPath = checkExisting(inNewSceneTar, tiffsStorage)
  File "/var/vsites/landsatfact-data-dev.nemac.org/project/geoprocessing/landsat
    unzipTIFgap(inTarPath, neededBands, extractedRoot)
  File "/var/vsites/landsatfact-data-dev.nemac.org/project/geoprocessing/landsat
    tar = tarfile.open(inTar)
  File "/usr/lib64/python2.7/tarfile.py", line 1665, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

**Comment by geoderek** [comment]
This ended up being an issue because we had run out of space on the server.  But, the error-handling could still be added to improve things.

**Comment by mwhutchi** [comment]
We seem to be running into this problem again, except in this case, it seems to actually be a bum tar file, which causes the geoprocessing to come to a halt. 

The tar files (3 of them) seem to be corrupt with no data in them.

**Comment by mwhutchi** [comment]
In looking at the products through Earth Explorer, I notice that the scenes that are corrupt also are not available to download (even though it is listed with today's acquisition date). So maybe they are somehow missing from EROS but the script is still trying to download them and returning with a bum tar file. The three that are "corrupt" or missing, thus throwing off the geoprocessing script are:
LE70180372015194EDC00
LE70180392015194EDC00
LE70180402015194EDC00

**Comment by geoderek** [comment]
I have seen this issue also.  I think it happens when the metadata sees 
that there is a new product. However, as you have found that product is 
not available to download.  I think the solution is to add some 
additional error-handling in the download script.

Derek

**Comment by mwhutchi** [comment]
Dave O. created a script that check the tar file size as a check. I will incorporate this into the lsf_cron after the tar download but before the geoprocessing script is run.
